### ISSUE TITLE
Implement new pseudo-class ':others()'

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/ExtendedCss#164]
@iSmokeMid69 commented on [Thu Feb 09 2023](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2285)

### Issue Details

Ublock Has :others() Operator..Which Keep Only A Selected Element Of A Page And Remove Everything Else..This Is Very Useful For Link Shortener Sites

Details -

subject:others()

Experimental.

    Description: Target all elements outside than the currently selected set of elements.
    Chainable: Yes.
    subject: Can be a plain CSS selector, or a procedural cosmetic filter.
    Examples:
        twitter.com##:matches-path(/^/home/) [data-testid="primaryColumn"]:others()
        nature.com##:matches-path(/^/articles//) :is(.c-breadcrumbs,.c-article-main-column):others()

Introduced in uBO 1.41.1b2

For any element feeding into others(), the resultset of the others() operator will include everything else except:

    the descendants of a subject element
    the ancestors of a subject element

The resultset will contains the siblings of a subject element except when those siblings are either a descendant or ancestor of another subject element.

Though this operator is unlikely to be used in default lists, it opens the door to create specialized filter lists which purpose is some sort of "reader mode", where everything else than a selected set of elements are hidden from view.

Related discussion:

    https://www.reddit.com/r/uBlockOrigin/comments/slyjzp/

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/2480

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/2099

**Comment by ameshkov** [comment]
Sounds as if it should be handled via rules conversion isn't it?

* `[data-testid="primaryColumn"]:others()` -> `:not([data-testid="primaryColumn"])`

**Comment by ameshkov** [comment]
I might be missing something, but `:not(selector)` seems to be exactly the same thing as `selector:others()`.

As I recall, `:not` is not fully supported in uBO, maybe that's the reason why a new modifier was required.

**Comment by ameshkov** [comment]
I assumed it does from the issue text:

> Ublock Has :others() Operator..Which Keep Only A Selected Element Of A Page And Remove Everything Else..This Is Very Useful For Link Shortener Sites

**Comment by ameshkov** [comment]
Ah, then it's even easier, `{ remove: true }` is not needed.

**Comment by krystian3w** [comment]
`:not(bla-bla-car)` don't hide parents in CSS?

```css
<body>
 <div>
   <bla-bla-car> don't hide my parent div and grandparent body! </bla-bla-car>
 </div>
</body>
```

**Comment by ameshkov** [comment]
Ah, now it makes perfect sense to me, thank you!

**Comment by ameshkov** [comment]
Then I guess it can be rewritten this way, right?

`[data-testid="primaryColumn"]:others() -> :not(:has([data-testid="primaryColumn"]))`

**Comment by u-RraaLL** [comment]
For only showing `.TimelineItem` (comments here), this would also work on uBO (just like `##.TimelineItem:others()`), but doesn't on Adguard (hides everything, even itself).

    ##:not(.TimelineItem *):not(:has(.TimelineItem *))

**Comment by slavaleleka** [comment]
not yet sir

**Comment by BlazeFTL** [comment]
Any progress update on this ?🙃

**Comment by slavaleleka** [comment]
@BlazeFTL it hasn't been yet _planned_ to be implemented soon

**Comment by krystian3w** [comment]
Someone can check these:

```CSS
:root :not([data-testid="primaryColumn"]) {
    display: none !important
}
```

If works then maybe possible shutdown JS implementation in favor native CSS.

**Comment by krystian3w** [comment]
In native CSS this seems to be the closest:

```CSS
:root { visibility: hidden !important }
:root [data-testid="primaryColumn"],
:root .TimelineItem { visibility: visible !important }
```

with little chance of hiding gaps left by invisible elements. RraaLL idea is not CSS "selector" (that is procedular selector) so do not works in Chrome 105-109 and Firefox 115 (latter I can check in Safari 17.2, Firefox Nightly and Chrome Canary).

**Comment by krystian3w** [comment]
<div id="CSS4">

With CSS4 should run at page:

```css
body :not(.TimelineItem, .TimelineItem *, :has(.TimelineItem)) { 
    display: none !important
}

/* First protect element, second child, last one 'root'. */

body :not([data-testid="primaryColumn"], [data-testid="primaryColumn"] *, :has([data-testid="primaryColumn"])) {
    display: none !important
}
```

Gaps gone, looks works based on ExtCSS library.

It remains to be assessed whether it is worth replacing comma elements to three "`:not`" and how much more resource-intensive it is than the JavaScript version.

</div>

___
___


<details> <summary>In native CSS3 this seems to be the closest:</summary>

> https://caniuse.com/css-not-sel-list (Chromium 88+, Firefox 84+, Safari 9+)

```CSS
body :not(.TimelineItem, .TimelineItem *, [data-testid="primaryColumn"], [data-testid="primaryColumn"] *) {
    visibility: hidden !important;
  /* at own risk in huge DOM tree:
    padding: 0 !important;
    margin: 0 !important;
    height: 0 !important */
}
:root [data-testid="primaryColumn"],
:root .TimelineItem { visibility: visible !important }
```

with little chance of hiding gaps left by invisible elements. 

</details>



___
___

<details> <summary>Hiding on Chrome 1*-87, Firefox 1*-83, Safari 1*-8 may need (legacy browsers - mostly CSS 2.1):</summary>

```CSS 
:root { visibility: hidden !important }
:root [data-testid="primaryColumn"],
:root .TimelineItem { visibility: visible !important }
```

(With harder implementation hide gaps). 

</details>
